version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: todo-app-backend
    container_name: todo-app-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    volumes:
      - data-volume:/tmp/DB
    ports:
      - "27017:27017"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: todo-app-frontend
    container_name: todo-app-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
    data-volume:
